### ISSUE TITLE
[NRCE] learn smartplug

### ISSUE THREAD

**Issue by Lionel642** [enocean-js/enocean-js#129]
Hi;

so just got an encoean plug ([nodon ASP-2-1-01](https://nodon.fr/nodon/prise-intelligente-metering-enocean/), EEP D2-01-0B), tested it with a physical 4 rocker, was able to control it from there, no problem. 

Then reseted the plug and thought I would be able to get it to learn node-red using [the second sample from the node-red-contrib-enocean page](https://flows.nodered.org/flow/0ab5bbccc5b4457db66bf81442228aaf), but got nothing, the plug stays in learn mode, and does not learn my system.

Using node-red 0.19.4, node-red-contrib-enocean 0.5.5, it is working fine with the physical 4 rockers I have, got messages in node-red.

Any idea? (not much documentation...)

Thanks;
Lionel

**Comment by Holger-Will** [comment]
yes, the same issue as #127 the issue here is twofold:

1. the 4 rocker uses f6-03-01 which unfortunately is not supported by nodeon devices. I will revert back to f6-02-01 which is supported. for the time being, you can use the sample flow from the aforementioned  issue.
2. d2-01-* eep description was flawed and is now fixed in my locaal branch. I will soon publish a new version with that patch. that will allow you to control even more aspects of your device

i will let you know when the new version is online

**Comment by Holger-Will** [comment]
published v0.6.0

* support for UTE teach in response for bidirectional teach in (experimatal)
* fix eep d2-01-*
* fix generating 4BS teach in  telegrams

should be in the palette manager in 15 min.

**Comment by Lionel642** [comment]
Hi;

thanks for the reactivity! so updated to 0.6.0, restarted node-red, imported afore mentionned work around, now works, thanks.

Lionel
